;; ;;; cc65 -DPROGSIZE -Oi gives smallest code
;;; 
;;; sim 2903
;;; tap 3260

;;; (- #x13e #x0) = 318 bytes... + lib (- 2903 318)= 2585
;;; MC: 274 bytes ... +lib

ca65 V2.18 - N/A
Main file   : Input/byte-sieve-malloc.s
Current file: Input/byte-sieve-malloc.s

000000r 1               ;
000000r 1               ; File generated by cc65 v 2.18 - N/A
000000r 1               ;
000000r 1               	.fopt		compiler,"cc65 v 2.18 - N/A"
000000r 1               	.setcpu		"6502"
000000r 1               	.smart		on
000000r 1               	.autoimport	on
000000r 1               	.case		on
000000r 1               	.debuginfo	off
000000r 1               	.importzp	sp, sreg, regsave, regbank
000000r 1               	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
000000r 1               	.macpack	longbranch
000000r 2               .macro  jeq     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                       bne     *+5
000000r 2                       jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               beq     Target
000000r 2                       .else
000000r 2                               bne     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jne     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               beq     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bne     Target
000000r 2                       .else
000000r 2                               beq     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jmi     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bpl     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bmi     Target
000000r 2                       .else
000000r 2                               bpl     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jpl     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bmi     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bpl     Target
000000r 2                       .else
000000r 2                               bmi     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jcs     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bcc     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bcs     Target
000000r 2                       .else
000000r 2                               bcc     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jcc     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bcs     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bcc     Target
000000r 2                       .else
000000r 2                               bcs     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jvs     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bvc     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bvs     Target
000000r 2                       .else
000000r 2                               bvc     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               .macro  jvc     Target
000000r 2                       .if     .match(Target, 0)
000000r 2                               bvs     *+5
000000r 2                               jmp     Target
000000r 2                       .elseif .def(Target) .and .const((*-2)-(Target)) .and ((*+2)-(Target) <= 127)
000000r 2                               bvc     Target
000000r 2                       .else
000000r 2                               bvs     *+5
000000r 2                               jmp     Target
000000r 2                       .endif
000000r 2               .endmacro
000000r 2               
000000r 1               	.forceimport	__STARTUP__
000000r 1               	.import		_malloc
000000r 1               	.import		_printf
000000r 1               	.export		_n
000000r 1               	.export		_c
000000r 1               	.export		_i
000000r 1               	.export		_p
000000r 1               	.export		_k
000000r 1               	.export		_m
000000r 1               	.export		_flag
000000r 1               	.export		_main
000000r 1               
000000r 1               .segment	"RODATA"
000000r 1               
000000r 1               L0034:
000000r 1  25 75 00     	.byte	$25,$75,$00
000003r 1               
000003r 1               .segment	"BSS"
000000r 1               
000000r 1               _n:
000000r 1  00 00        	.res	2,$00
000002r 1               _c:
000002r 1  00 00        	.res	2,$00
000004r 1               _i:
000004r 1  00 00        	.res	2,$00
000006r 1               _p:
000006r 1  00 00        	.res	2,$00
000008r 1               _k:
000008r 1  00 00        	.res	2,$00
00000Ar 1               _m:
00000Ar 1  00 00        	.res	2,$00
00000Cr 1               _flag:
00000Cr 1  00 00        	.res	2,$00
00000Er 1               
00000Er 1               ; ---------------------------------------------------------------
00000Er 1               ; int __near__ main (void)
00000Er 1               ; ---------------------------------------------------------------
00000Er 1               
00000Er 1               .segment	"CODE"
000000r 1               
000000r 1               .proc	_main: near
000000r 1               
000000r 1               .segment	"CODE"
000000r 1               
000000r 1               ;
000000r 1               ; m= SIZE;
000000r 1               ;
;;; Not using zp: + 2
000000r 1  A2 20        	ldx     #$20
000002r 1  A9 00        	lda     #$00
000004r 1  8D rr rr     	sta     _m
000007r 1  8E rr rr     	stx     _m+1
00000Ar 1               ;
00000Ar 1               ; flag= malloc(m);
00000Ar 1               ;
;;; clever ruse AX -4
00000Ar 1  20 rr rr     	jsr     _malloc
00000Dr 1  8D rr rr     	sta     _flag
000010r 1  8E rr rr     	stx     _flag+1
000013r 1               ;
000013r 1               ; n=0; do {
000013r 1               ;
;;; no zp +2
000013r 1  A9 00        	lda     #$00
000015r 1  8D rr rr     	sta     _n
000018r 1  8D rr rr     	sta     _n+1
00001Br 1               ;
00001Br 1               ; c=0;
00001Br 1               ;
;;; +2
00001Br 1  A9 00        L0009:	lda     #$00
00001Dr 1  8D rr rr     	sta     _c
000020r 1  8D rr rr     	sta     _c+1
000023r 1               ;
000023r 1               ; i=0; do flag[i++]= 1; while(i<m);
000023r 1               ;
;;; good reuse -2
000023r 1  8D rr rr     	sta     _i
000026r 1  8D rr rr     	sta     _i+1

000029r 1  AD rr rr     L0010:	lda     _flag
00002Cr 1  AE rr rr     	ldx     _flag+1
;;; slow
00002Fr 1  20 rr rr     	jsr     pushax
000032r 1  AD rr rr     	lda     _i
000035r 1  AE rr rr     	ldx     _i+1
;;; hmmm
000038r 1  85 rr        	sta     regsave
00003Ar 1  86 rr        	stx     regsave+1
;;; ++i    -2 reuse AX
00003Cr 1  18           	clc
00003Dr 1  69 01        	adc     #$01
00003Fr 1  90 01        	bcc     L0015
000041r 1  E8           	inx
000042r 1  8D rr rr     L0015:	sta     _i
000045r 1  8E rr rr     	stx     _i+1

000048r 1  A5 rr        	lda     regsave
00004Ar 1  A6 rr        	ldx     regsave+1
00004Cr 1  20 rr rr     	jsr     tosaddax
00004Fr 1  85 rr        	sta     ptr1
000051r 1  86 rr        	stx     ptr1+1

;;; A=1 flag[]=1
000053r 1  A9 01        	lda     #$01
000055r 1  A0 00        	ldy     #$00
000057r 1  91 rr        	sta     (ptr1),y

;;; while (i<m);
000059r 1  AD rr rr     	lda     _i
00005Cr 1  CD rr rr     	cmp     _m
00005Fr 1  AD rr rr     	lda     _i+1
000062r 1  ED rr rr     	sbc     _m+1
000065r 1  90 C2        	bcc     L0010

000067r 1               ;
000067r 1               ; i=0; do {
000067r 1               ;
;;; Y=0 already ! -1 B
000067r 1  98           	tya
000068r 1  8D rr rr     	sta     _i
00006Br 1  8D rr rr     	sta     _i+1
00006Er 1               ;
00006Er 1               ; if (flag[i]) {
00006Er 1               ;
00006Er 1  AD rr rr     L001A:	lda     _flag
000071r 1  18           	clc
000072r 1  6D rr rr     	adc     _i
000075r 1  85 rr        	sta     ptr1
000077r 1  AD rr rr     	lda     _flag+1
00007Ar 1  6D rr rr     	adc     _i+1
00007Dr 1  85 rr        	sta     ptr1+1
00007Fr 1  B1 rr        	lda     (ptr1),y
;;; short jmp
000081r 1  F0 6D        	beq     L001D
000083r 1               ;
000083r 1               ; p= i+i+3;
000083r 1               ;
;;; 
000083r 1  AD rr rr     	lda     _i
000086r 1  18           	clc
000087r 1  6D rr rr     	adc     _i
;;; keeping Y=0 ???
00008Ar 1  48           	pha

00008Br 1  AD rr rr     	lda     _i+1
00008Er 1  6D rr rr     	adc     _i+1
000091r 1  AA           	tax
000092r 1  68           	pla
;;; add 3 good
000093r 1  18           	clc
000094r 1  69 03        	adc     #$03
000096r 1  90 01        	bcc     L0022
000098r 1  E8           	inx

000099r 1  8D rr rr     L0022:	sta     _p
00009Cr 1  8E rr rr     	stx     _p+1
00009Fr 1               ;
00009Fr 1               ; k=i+p; while(k<m) {
00009Fr 1               ;
00009Fr 1  AD rr rr     	lda     _i
0000A2r 1  18           	clc
0000A3r 1  6D rr rr     	adc     _p
0000A6r 1  8D rr rr     	sta     _k
0000A9r 1  AD rr rr     	lda     _i+1
0000ACr 1  6D rr rr     	adc     _p+1
0000AFr 1  4C rr rr     	jmp     L003C
0000B2r 1               ;
0000B2r 1               ; flag[k]= 0;
0000B2r 1               ;
0000B2r 1  AD rr rr     L0025:	lda     _flag
0000B5r 1  18           	clc
0000B6r 1  6D rr rr     	adc     _k
0000B9r 1  85 rr        	sta     ptr1
0000BBr 1  AD rr rr     	lda     _flag+1
0000BEr 1  6D rr rr     	adc     _k+1
0000C1r 1  85 rr        	sta     ptr1+1
0000C3r 1  A9 00        	lda     #$00
0000C5r 1  91 rr        	sta     (ptr1),y
0000C7r 1               ;
0000C7r 1               ; k+=p;
0000C7r 1               ;
0000C7r 1  AD rr rr     	lda     _p
0000CAr 1  18           	clc
0000CBr 1  6D rr rr     	adc     _k
0000CEr 1  8D rr rr     	sta     _k
0000D1r 1  AD rr rr     	lda     _p+1
0000D4r 1  6D rr rr     	adc     _k+1
0000D7r 1  8D rr rr     L003C:	sta     _k+1
0000DAr 1               ;
0000DAr 1               ; k=i+p; while(k<m) {
0000DAr 1               ;
0000DAr 1  AD rr rr     	lda     _k
0000DDr 1  CD rr rr     	cmp     _m
0000E0r 1  AD rr rr     	lda     _k+1
0000E3r 1  ED rr rr     	sbc     _m+1
0000E6r 1  90 CA        	bcc     L0025
0000E8r 1               ;
0000E8r 1               ; ++c;
0000E8r 1               ;
0000E8r 1  EE rr rr     	inc     _c
0000EBr 1  D0 03        	bne     L001D
0000EDr 1  EE rr rr     	inc     _c+1
0000F0r 1               ;
0000F0r 1               ; ++i;
0000F0r 1               ;
0000F0r 1  EE rr rr     L001D:	inc     _i
0000F3r 1  D0 03        	bne     L0031
0000F5r 1  EE rr rr     	inc     _i+1
0000F8r 1               ;
0000F8r 1               ; } while(i<m);
0000F8r 1               ;
0000F8r 1  AD rr rr     L0031:	lda     _i
0000FBr 1  CD rr rr     	cmp     _m
0000FEr 1  AD rr rr     	lda     _i+1
000101r 1  ED rr rr     	sbc     _m+1
000104r 1  B0 03 4C rr  	jcc     L001A
000108r 1  rr           
000109r 1               ;
000109r 1               ; printf("%u", c);
000109r 1               ;
000109r 1  A9 rr        	lda     #<(L0034)
00010Br 1  A2 rr        	ldx     #>(L0034)
00010Dr 1  20 rr rr     	jsr     pushax
000110r 1  AD rr rr     	lda     _c
000113r 1  AE rr rr     	ldx     _c+1
000116r 1  20 rr rr     	jsr     pushax
000119r 1  A0 04        	ldy     #$04
00011Br 1  20 rr rr     	jsr     _printf
00011Er 1               ;
00011Er 1               ; ++n;
00011Er 1               ;
00011Er 1  EE rr rr     	inc     _n
000121r 1  D0 03        	bne     L0038
000123r 1  EE rr rr     	inc     _n+1
000126r 1               ;
000126r 1               ; } while(n<10);
000126r 1               ;
000126r 1  AD rr rr     L0038:	lda     _n+1
000129r 1  C9 00        	cmp     #$00
00012Br 1  D0 05        	bne     L003A
00012Dr 1  AD rr rr     	lda     _n
000130r 1  C9 0A        	cmp     #$0A
000132r 1  B0 03 4C rr  L003A:	jcc     L0009
000136r 1  rr           
000137r 1               ;
000137r 1               ; return c;
000137r 1               ;
000137r 1  AD rr rr     	lda     _c
00013Ar 1  AE rr rr     	ldx     _c+1
00013Dr 1               ;
00013Dr 1               ; }
00013Dr 1               ;
00013Dr 1  60           	rts
00013Er 1               
00013Er 1               .endproc
00013Er 1               
00013Er 1               
