;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_fun
	.export		_main

; ---------------------------------------------------------------
; int __near__ fun (int, int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fun: near

.segment	"CODE"

;
; int fun(int a, int b, int c, int d) {
;
	jsr     pushax
;
; return a? fun(a-1, b+1, c*2, d/2): a+b+c+d;
;
	ldy     #$07
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L0003
	iny
	jsr     ldaxysp
	jsr     decax1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     incax1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     asrax1
	jsr     _fun
	jmp     incsp8
L0003:	dey
	jsr     ldaxysp
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	jsr     ldax0sp
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
;
; }
;
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; return fun(0,0,1,65535u);
;
	jsr     push0
	jsr     push0
	lda     #$01
	jsr     pusha0
	ldx     #$FF
	txa
	jmp     _fun

.endproc

