AT%I
B;|=E;|(#,A)S
C==|=|<=|<|>=|>|!=
DAB
E!E|(E)|FCE
FG+G|G-G|G
GH*H|H/H|H
H%D|*%I|*%I=E|%I=E|O%I|%IO|%I(#,E)
I
J
K
L
M
N
O++|--
PDP|
Q
R
S;|{#;S}|return E;|if(E)SU|while(E)S|E;
Tint*|int|char*|char
U|elseS
V
W
X
Y
Z
