#!/bin/env perl

# Typical output line from sim65 --trace
#
# 9180701      26130074
#   E181  A0 04     ldy  #$04
#   A=0A X=00 Y=01 S=F7
#   Flags=nvdIzC    SP=FF89

%freq=();

while(<>) {
#    if (/^\s*(\d+)\s+(\d+)\s+(\x+).*S=(\x+)/) {
    if (/^\s*(\d+)\s+(\d+)\s+([\da-fA-F]+)/) {
        my ($ninstr, $cyc, $addr, $S)= ($1, $2, $3, $4);
        $freq{$addr}++;
#        print STDERR "$cyc\t$addr\t$S\n";
        print STDERR "$ninstr\r";
    } else {
        # anything else print (stdout)
        # (mixed with trace lines interrrupted)
        print;
    }

}


# report
if (($ninstr % 1000)==0) {
    foreach $a (sort(keys %freq)) {
        print "$a : ".$freq{$a}."\n";
    }
}
