#!/bin/env perl

# reading ./pf65 file.trace > file.pf
# showing $name.map labels interleaved

# Usage: ./pfmap NAME file.pf

$name= shift @ARGV;
$pf= shift @ARGV;

print "========== $name ==========\n";

$start= $addr= "0000";

my $all;
my %freq;
my %asm;

open(PF, $pf) or die "no .pf";
while(<PF>) {
    if (/([\da-hA-H]+)\s+:\s+(\d+)\s+(.*)/) {
        $freq{$1}= $2;
        $asm{$1}= $3;
    } elsif (/^0 0 \$([\da-hA-h]+)\s+(.*)/) {
        $freq{$1}++;
        $asm{$1}= $2;
    } else {
        #print STDERR "%%$_";
    }
}
close(PF);

$names= "";
my %tots;
my %maxcount;
$all= 0;

open(IN, $name.".syms") or die "no .syms";
while(<IN>) {
    # 00ADDR   42   name
    if (/^..([0-9a-fA-F]+)\s+(\d+)\s+(\w+)$/) {
        $a= $1; $name= $3;
        if ($a eq $addr) {
        } else {
            # end names at address
            $addr= $a;
            print "\n------------------------------\n";
            # print memory [$start,$addr[
            $max= $total= 0;
            $alphas= "";
            for $m (hex($start)..(hex($addr)-1)) {
                $x= sprintf("%04X", $m);
                $v= $freq{$x};
                if ($v) {
                    # TODO: should be counting cyc, lol
                    $total+= $v;
                    $max= $v if $v > $max;
                    print sprintf("$x %8d        %s\n", $v, $asm{$x});
                }
            }
            $start= $addr;

            if ($total) {
                $tots{$names}= $total;
                $all+= $total;
                print "\nmax: $max\t total: $total\n\n\n";
                $maxcount{$names}= $max;
            }
            $names = "";
        }
        print "\n";
        print "  ".$name;
        $names.= "$name ";
    } else {
        # ??
# TODO: "few" items
#        print "\n%%$_";
    }

}
close(IN);

# report summary per "$names"

# Trace last line: cyc/ninstr = 
# 2.84619735707003372284 cyc/instr

$cpi= 26130141/9180720;
$hz= 1000000;

print "\n====================================\n";
foreach $n (sort { $tots{$a} <=> $tots{$b} } keys %tots) {
    if (1) {
        $cyc= int($cpi * $tots{$n});
        print sprintf("%4.1f%% %5.1fs\t# %7d\t= %10d: $n\n", 100*$tots{$n}/$all, $cyc/$hz, $maxcount{$n}, $cyc);
    } else {
        print $tots{$n}."\t= $n\n";
    }
}

print sprintf("\n\nTOTAL:\t%5.2fs\t%d c\t$all instr\n", $cpi*$all/$hz, $cpi*$all);

