#!/bin/env perl

$name= shift @ARGV;
$snap= shift @ARGV;

print "========== $name ==========\n";

$start= $addr= "0000";

$fullwidth= 0xff00; # "space"
my $all;
my @ram;

open(SNAP, $snap) or die "no snap";
read(SNAP, $all, 65536) or die "no read";
close(SNAP);

binmode(STDOUT, ":utf8");

push @ram, unpack "C*", $all;

open(IN, $name.".syms") or die "no .syms";
while(<IN>) {
    if (/^..([0-9a-fA-F]+)\s+(\d+)\s+(\w+)$/) {
        $a= $1; $name= $3;
        if ($a eq $addr) {
        } else {
            # end names at address
            $addr= $a;
            print "\n------------------------------";
            # print memory [$start,$addr[
            $n= 0;
            $alphas= "";
            for $m (hex($start)..(hex($addr)-1)) {
                if ($n % 16==0) {
                    printf(" $alphas\n");
                    $alphas= "";
                    # newline
                    printf("%04X: ", $m);
                }

                $v= $ram[$m];
                $w= $v & 0x7f;

                # print it
                if (1) {

                    # hexdump

                    printf("%02x ", $v);

                    if ($w==0) { $alphas.= "\$"; }
                    elsif ($w>32 && $w<126) {
                        if ($v & 0x80) {
                            $alphas.= sprintf("\e[7m%c\e[0m", $w);
                        } else {
                            $alphas.= sprintf("%c", $w);
                        }
                    } else { $alphas.= "."; }
                        

                } else {

                    # fancy inline widechars

                    if ($w==32) { print "  "; }
                    elsif ($w>32 && $w<126) {
                        print (($v & 0x80)? "\e[7m": "");
                        printf("%c", $w+$fullwidth-32);
                        print "\e[0m";
                    } else { printf("%02x", $v); }

                }

                ++$n;
            }

            # print overflow
            while(($n % 16)) { ++$n; print "   "; }
            printf(" $alphas");

            print "\n\n\n\n$addr";
            $start= $addr;
        }
        print "  ".$name;
    } else {
        print "\n%%$_";
    }

}
close(IN);
close(SNAP);
